### ISSUE TITLE
Suggestions on handle the unpublished data

### ISSUE THREAD

**Issue by moggces** [moggces/CurveVisualizationGUI4Tox21#2]
Similar issue is applied to the Activity profiler. 

I used to put them all into the public and wrote a function limiting downloads for only published ones. 
But the unpublished assays could have unfinished annotations and tend to have more undisclosed issues (since haven't explored enough). 

Does that make sense that  the latest apps can work on sandbox-staging but not to the sandbox (public)?

**Comment by shapiromatron** [comment]
@moggces sorry just saw this; we can do that. I'd prefer if we used a single codebase for both staging and production, and then based on an environment variable if production use these data, else use those, does that make sense?

**Comment by moggces** [comment]
use Sys.setenv/Sys.getenv to set an environment variable (e.g., AP_DEV) and use it to control the dataset loading in R. The value variable can be set differently between staging and production sandbox.
